apiVersion: apps/v1
kind: Deployment
metadata:
  name: add-note
spec:
  replicas: 1
  selector:
    matchLabels:
      app: add-note
  template:
    metadata:
      labels:
        app: add-note
    spec:
      containers:
        - name: add-note
          image: basith1519/add-note:v1.4
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: add-note
spec:
  selector:
    app: add-note
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 80
  type: LoadBalancer