apiVersion: apps/v1
kind: Deployment
metadata:
  name: host
spec:
  replicas: 1
  selector:
    matchLabels:
      app: host
  template:
    metadata:
      labels:
        app: host
    spec:
      containers:
        - name: host
          image: basith1519/host:v1.1
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: host
spec:
  selector:
    app: host
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer