apiVersion: apps/v1
kind: Deployment
metadata:
  name: list-notes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: list-notes
  template:
    metadata:
      labels:
        app: list-notes
    spec:
      containers:
        - name: list-notes
          image: basith1519/list-notes:v1.2
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: list-notes
spec:
  selector:
    app: list-notes
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 80
  type: LoadBalancer