apiVersion: apps/v1
kind: Deployment
metadata:
  name: view-notes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: view-notes
  template:
    metadata:
      labels:
        app: view-notes
    spec:
      containers:
        - name: view-notes
          image: basith1519/view-note:v1.0
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: view-notes
spec:
  selector:
    app: view-notes
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 80
  type: LoadBalancer